// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0yM7IrwMaivl4nTQ894IFn0Ly0Oa6Ksg',
    appId: '1:1003511952703:web:d88574a42a497f27cc0f8a',
    messagingSenderId: '1003511952703',
    projectId: 'nutrimate-50c58',
    authDomain: 'nutrimate-50c58.firebaseapp.com',
    storageBucket: 'nutrimate-50c58.firebasestorage.app',
    measurementId: 'G-7K0QDJKYDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv1CDlItZiodA_63zBJZy58NPIzWMEr9g',
    appId: '1:1003511952703:android:b31243e48b434140cc0f8a',
    messagingSenderId: '1003511952703',
    projectId: 'nutrimate-50c58',
    storageBucket: 'nutrimate-50c58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTMUWnOgzIhJEtX9zXQGg-vofvwIHAbIk',
    appId: '1:1003511952703:ios:f7ad99ce301692b4cc0f8a',
    messagingSenderId: '1003511952703',
    projectId: 'nutrimate-50c58',
    storageBucket: 'nutrimate-50c58.firebasestorage.app',
    iosBundleId: 'com.example.flNutrimate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTMUWnOgzIhJEtX9zXQGg-vofvwIHAbIk',
    appId: '1:1003511952703:ios:f7ad99ce301692b4cc0f8a',
    messagingSenderId: '1003511952703',
    projectId: 'nutrimate-50c58',
    storageBucket: 'nutrimate-50c58.firebasestorage.app',
    iosBundleId: 'com.example.flNutrimate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0yM7IrwMaivl4nTQ894IFn0Ly0Oa6Ksg',
    appId: '1:1003511952703:web:0c55994659674cfacc0f8a',
    messagingSenderId: '1003511952703',
    projectId: 'nutrimate-50c58',
    authDomain: 'nutrimate-50c58.firebaseapp.com',
    storageBucket: 'nutrimate-50c58.firebasestorage.app',
    measurementId: 'G-GQMQEHFG15',
  );
}
